apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-app-config
  namespace: demo-app
  labels:
    app: demo-app
    env: preprod
    team: pokerstars-ita
    version: "v1.1"
data:
  APP_ENV: "preprod"
  APP_PORT: "8080"
  APP_NAME: "demo-pokerstars"
  LOG_LEVEL: "debug"
  DB_HOST: "demo-postgres"
  DB_PORT: "5432"
  FEATURE_FLAG_NEW_UI: "true"
  REGION: "ita"
