apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-frontend
  namespace: demo-app
  labels:
    app: demo-frontend
    version: "v1.2"
    env: preprod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-frontend
  template:
    metadata:
      labels:
        app: demo-frontend
        version: "v1.2"
    spec:
      containers:
        - name: frontend
          image: nginx:1.25-alpine
          ports:
            - containerPort: 80
          env:
            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: demo-app-config
                  key: APP_ENV
            - name: APP_NAME
              valueFrom:
                configMapKeyRef:
                  name: demo-app-config
                  key: APP_NAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: demo-app-secret
                  key: DB_PASSWORD
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: demo-frontend-svc
  namespace: demo-app
spec:
  type: NodePort
  selector:
    app: demo-frontend
  ports:
    - port: 80
      targetPort: 80
