apiVersion: v1
kind: Secret
metadata:
  name: demo-app-secret
  namespace: demo-app
type: Opaque
stringData:
  DB_PASSWORD: "supersecret123"
  API_KEY: "demo-api-key-abc123"
  JWT_SECRET: "jwt-secret-xyz789"
